spring.application.name=company-service
server.port=8570
eureka.instance.instance-id=${spring.application.name}:${random.value}

#
#LOCAL
spring.jpa.hibernate.show_sql=true
spring.jpa.hibernate.format_sql=true
spring.jpa.hibernate.use_sql_comments=false
spring.jpa.hibernate.type=all
eureka.client.serviceUrl.defaultZone = http://localhost:8555/eureka

# DB-Connnection
spring.datasource.url=jdbc:mysql://localhost:3306/ms_mybiz_company
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.cloud.loadbalancer.ribbon.enabled=false

#SWAGGER
springdoc.swagger-ui.path=/swagger-url.html
springdoc.api.docs.path=/api-docs

#Actuator
management.endpoints.web.exposure.include=*
