

# App Properties
jwtSecret= ZDaf9Aw3WW8ZqPymnGomc9y0KqsS/l/0yuwXdXrmYs7vvz8yQFhnjQW9HHeGIIGHQ+d4Xjer1wNtqdgbREFNTA==
jwtExpirationMs=900000
spring.application.name=authentication-service
#server.port=${PORT:0}
server.port=8557
eureka.instance.instance-id=${spring.application.name}:${random.value}

#LOCAL
eureka.client.serviceUrl.defaultZone = http://localhost:8555/eureka


#LOCAL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show_sql=true
spring.jpa.hibernate.format_sql=true
spring.jpa.hibernate.use_sql_comments=false
spring.jpa.hibernate.type=all

#LOCAL
spring.datasource.url=jdbc:mysql://localhost:3306/ms_mybiz_authendication
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.cloud.loadbalancer.ribbon.enabled=true
