spring.application.name=inventory-service
#server.port=${PORT:0}
server.port=8777
eureka.instance.instance-id=${spring.application.name}:${random.value}
#
##LOCAL
eureka.client.serviceUrl.defaultZone = http://localhost:8555/eureka

 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show_sql=true
spring.jpa.hibernate.format_sql=true
spring.jpa.hibernate.use_sql_comments=false
spring.jpa.hibernate.type=all

#LOCAL
spring.datasource.url=jdbc:mysql://localhost:3306/ms_mybiz_inventory
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.cloud.loadbalancer.ribbon.enabled=false

springdoc.swagger-ui.path=/swagger-url.html
springdoc.api.docs.path=/api-docs

management.endpoints.web.exposure.include=*
